apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: homeautomation-web
  name: homeautomation-web
spec: 
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ ternary 1 0 (gt (int .Values.replicaCount) 1) }}
      maxSurge: 1
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector: 
    matchLabels: 
      app: homeautomation-web
  template: 
    metadata: 
      labels: 
        app: homeautomation-web
        {{- if eq .Values.image.tag "latest" }}
        date: "{{ now | unixEpoch }}"
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec: 
      containers: 
      - image: {{ .Values.image.repository }}:{{ required "image.tag is required" .Values.image.tag }}
        name: homeautomation-web
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources: {{ toYaml .Values.resources | nindent 10 }}
        env:
        {{- range $key, $val := .Values.env.secret }}
        - name: {{ $key }}
          valueFrom:
            secretKeyRef:
              name: homeautomation-web
              key: {{ $key }}
        {{- end }}
        {{- range $key, $val := .Values.env.normal }}
        - name: {{ $key }}
          value: {{ $val | quote }}
        {{- end }}
        ports:
        - containerPort: 8080
        startupProbe:
          httpGet:
            scheme: HTTP
            port: 8080
            path: /healthz
          periodSeconds: 5
          failureThreshold: 6
      nodeSelector:
        kubernetes.io/os: linux