apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homeautomation
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - {{ required "ingress.host is required" .Values.ingress.host }}
    secretName: homeautomation-tls
  rules:
  - host: {{ required "ingress.host is required" .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: homeautomation-web
            port:
              number: 80