apiVersion: v1
kind: Secret
metadata:
  name: homeautomation-web
  labels:
    app: homeautomation-web
type: Opaque
stringData:
  {{- range $key, $val := .Values.env.secret }}
  {{ $key }}: {{ $val | quote }}
  {{- end}}